name: Temporary VPS SSH

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Generate SSH Key
        run: |
          ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N "" -C "github-actions@vps"
          echo "Public key:"
          cat ~/.ssh/id_ed25519.pub

      - name: Install SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo mkdir -p /var/run/sshd
          sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
          sudo service ssh start

      - name: Add generated key to authorized_keys
        run: |
          mkdir -p ~/.ssh
          cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          chmod 700 ~/.ssh

      - name: Show connection info
        run: |
          echo "Connect using:"
          echo "ssh -i ~/.ssh/id_ed25519 root@$(curl -s ifconfig.me)"
