name: Temporary V2Ray VPS

on:
  workflow_dispatch:

jobs:
  run-v2ray:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      - name: Install V2Ray
        run: |
          bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

      - name: Setup default config
        run: |
          sudo tee /usr/local/etc/v2ray/config.json > /dev/null <<EOF
          {
            "inbounds": [
              {
                "port": 1080,
                "listen": "0.0.0.0",
                "protocol": "socks",
                "settings": {
                  "auth": "noauth",
                  "udp": true
                }
              }
            ],
            "outbounds": [
              {
                "protocol": "freedom",
                "settings": {}
              }
            ]
          }
          EOF

      - name: Run V2Ray
        run: |
          sudo systemctl stop v2ray || true
          sudo /usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json &
          echo "V2Ray is running on port 1080"
